### ISSUE TITLE
Can't log into Teams

### ISSUE THREAD

**Issue by devanshj-groflex** [rguptagroflex/groflex-huro#2]
I can't log into Teams, here's the error...
![image](https://github.com/rguptagroflex/groflex-huro/assets/155975083/3feeb2a7-bc99-4eb2-ba61-1ba553d59a89)

cc @Keshav-Groflex @rguptagroflex

**Comment by Keshav-Groflex** [comment]
Hi,

Are you able to login now?

On 2024-01-20 11:00, devanshj-groflex wrote:

> I can't log into Teams, here's the error...
> image.png (view on web) [1]
> 
> cc @Keshav-Groflex [2] @rguptagroflex [3]
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/rguptagroflex/groflex-huro/assets/155975083/3feeb2a7-bc99-4eb2-ba61-1ba553d59a89
[2] https://github.com/Keshav-Groflex
[3] https://github.com/rguptagroflex
[4] https://github.com/rguptagroflex/groflex-huro/issues/2
[5]

**Comment by devanshj-groflex** [comment]
Closing as the issue is being discussed elsewhere
